/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AppThucDon.dao.FormDangNhap;

import AppThucDon.database.Database;
import AppThucDon.view.Mainlayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

public class EditProfileFirstTime extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditProfileFirstTime.class.getName());

    private String username;

    private String avatarPath = "";

    /*
constructor nhận username
     */
    public EditProfileFirstTime(
            String username
    ) {

        initComponents();
        setTitle("JavaCook - Hồ sơ");

        Image con = new ImageIcon(
                getClass().getResource("/images/logo.png"))
                .getImage();

        setIconImage(con);
        txtBio.setBorder(
                BorderFactory.createCompoundBorder(
                        BorderFactory.createLineBorder(new Color(232, 181, 53), 2),
                        BorderFactory.createEmptyBorder(8, 8, 8, 8)
                ));

        ImageIcon icon = new ImageIcon(getClass().getResource(""));
        Image img = icon.getImage().getScaledInstance(
                lblAvatar.getWidth(),
                lblAvatar.getHeight(),
                Image.SCALE_SMOOTH);

        lblAvatar.setIcon(new ImageIcon(img));

        getContentPane().setBackground(new Color(255, 250, 242));

        btnChooseAvatar.setFocusPainted(false);
        btnChooseAvatar.setBorderPainted(false);
        btnChooseAvatar.setCursor(new Cursor(Cursor.HAND_CURSOR));

        lblTitle.setFont(new Font("Segoe UI", Font.BOLD, 34));
        lblTitle.setForeground(new Color(150, 98, 20));
        lblDescription.setFont(new Font("Segoe UI", Font.ITALIC, 14));
        lblDescription.setForeground(new Color(120, 120, 120));
        lblAvatar.setBorder(
                BorderFactory.createLineBorder(
                        new Color(230, 190, 90), 2));

        lblAvatar.setHorizontalAlignment(SwingConstants.CENTER);

        txtDisplayName.setBorder(
                BorderFactory.createLineBorder(
                        new Color(232, 181, 53), 2));

        txtDisplayName.setFont(new Font("Segoe UI", Font.PLAIN, 16));
        txtBio.setLineWrap(true);
        txtBio.setWrapStyleWord(true);
        btnChooseAvatar.setBackground(Color.WHITE);
        btnChooseAvatar.setForeground(new Color(150, 98, 20));
        btnSave.setBackground(new Color(247, 192, 67));
        btnSave.setForeground(Color.WHITE);
        btnSave.setFont(new Font("Segoe UI", Font.BOLD, 16));

        btnSave.setBackground(new Color(255, 206, 84));

        btnSave.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                btnSave.setBackground(new Color(244, 180, 0));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                btnSave.setBackground(new Color(255, 206, 84));
            }
        });

        setSize(AppConfig.WIDTH, AppConfig.HEIGHT);
        setLocationRelativeTo(null);

        this.username = username;

        // load dữ liệu cũ
        txtDisplayName.setText(
                CurrentUser.displayName
        );

        txtBio.setText(
                CurrentUser.bio
        );

        avatarPath
                = CurrentUser.avatar;

        try {

            if (avatarPath != null
                    && !avatarPath.isEmpty()) {

                ImageIcon avatarIcon = new ImageIcon(avatarPath);

                Image avatarImg = avatarIcon.getImage().getScaledInstance(
                        150,
                        150,
                        Image.SCALE_SMOOTH
                );

                lblAvatar.setText("");

                lblAvatar.setIcon(new ImageIcon(avatarImg));

            }

        } catch (Exception e) {

            e.printStackTrace();

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDisplayName = new javax.swing.JLabel();
        txtDisplayName = new javax.swing.JTextField();
        lblBio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtBio = new javax.swing.JTextArea();
        btnSave = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblAvatarTitle = new javax.swing.JLabel();
        lblAvatar = new javax.swing.JLabel();
        btnChooseAvatar = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblDisplayName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDisplayName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N
        lblDisplayName.setText("Tên hiển thị");

        txtDisplayName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDisplayName.addActionListener(this::txtDisplayNameActionPerformed);

        lblBio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblBio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comment.png"))); // NOI18N
        lblBio.setText("Giới thiệu bản thân");

        txtBio.setColumns(20);
        txtBio.setRows(5);
        jScrollPane1.setViewportView(txtBio);

        btnSave.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diskette.png"))); // NOI18N
        btnSave.setText("Lưu thay đổi");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTitle.setText("Hoàn thiện hồ sơ");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAvatarTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAvatarTitle.setText("Ảnh đại diện");
        jPanel1.add(lblAvatarTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, 112, 21));

        lblAvatar.setBackground(new java.awt.Color(153, 153, 153));
        lblAvatar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAvatar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 190, 70), 2));
        lblAvatar.setMaximumSize(new java.awt.Dimension(150, 150));
        lblAvatar.setMinimumSize(new java.awt.Dimension(150, 150));
        lblAvatar.setPreferredSize(new java.awt.Dimension(150, 150));
        jPanel1.add(lblAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 150, -1));

        btnChooseAvatar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnChooseAvatar.setForeground(new java.awt.Color(255, 209, 92));
        btnChooseAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo-camera-interface-symbol-for-button.png"))); // NOI18N
        btnChooseAvatar.setText("Chọn ảnh");
        btnChooseAvatar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnChooseAvatar.addActionListener(this::btnChooseAvatarActionPerformed);
        jPanel1.add(btnChooseAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 570, 150, 50));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fb342928-df51-4df9-9354-21d282ce.png"))); // NOI18N
        lblBackground.setText("jLabel6");
        jPanel1.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 530, 800));

        lblDescription.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDescription.setText("Cập nhật thông tin của để mọi người biết đến bạn");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(150, 150, 150));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/info.png"))); // NOI18N
        jLabel1.setText("Thông tin này sẽ hiển thị trên trang cá nhân của bạn.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDisplayName, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBio, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTitle)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(txtDisplayName)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(2102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDisplayName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDisplayName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(lblBio, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1885, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDisplayNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDisplayNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDisplayNameActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {

            Connection conn
                    = Database.getConnection();

            String sql
                    = "UPDATE Users "
                    + "SET "
                    + "DisplayName=?,"
                    + "Avatar=?,"
                    + "Bio=? "
                    + "WHERE Username=?";

            PreparedStatement ps
                    = conn.prepareStatement(
                            sql
                    );

            ps.setString(
                    1,
                    txtDisplayName.getText()
            );

            ps.setString(
                    2,
                    avatarPath
            );

            ps.setString(
                    3,
                    txtBio.getText()
            );

            ps.setString(
                    4,
                    username
            );

            ps.executeUpdate();
            CurrentUser.username
                    = username;

            CurrentUser.displayName
                    = txtDisplayName.getText();

            CurrentUser.bio
                    = txtBio.getText();

            CurrentUser.avatar
                    = avatarPath;

            JOptionPane.showMessageDialog(
                    this,
                    "Lưu thành công!"
            );

            Mainlayout main
                    = new Mainlayout();

            main.setVisible(
                    true
            );

            dispose();

        } catch (Exception e) {

            e.printStackTrace();

        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnChooseAvatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseAvatarActionPerformed
        try {

            JFileChooser chooser
                    = new JFileChooser();

            int result
                    = chooser.showOpenDialog(this);

            if (result
                    == JFileChooser.APPROVE_OPTION) {

                File file
                        = chooser.getSelectedFile();

                String fileName
                        = System.currentTimeMillis()
                        + "_"
                        + file.getName();

                File dir
                        = new File(
                                "uploads"
                        );

                if (!dir.exists()) {

                    dir.mkdirs();

                }

                File save
                        = new File(
                                dir,
                                fileName
                        );

                Files.copy(
                        file.toPath(),
                        save.toPath(),
                        StandardCopyOption.REPLACE_EXISTING
                );

                avatarPath
                        = save.getPath();

                ImageIcon icon
                        = new ImageIcon(
                                avatarPath
                        );

                Image img
                        = icon.getImage()
                                .getScaledInstance(
                                        150,
                                        150,
                                        Image.SCALE_SMOOTH
                                );

                lblAvatar.setText("");

                lblAvatar.setIcon(
                        new ImageIcon(
                                img
                        )
                );

            }

        } catch (Exception e) {

            e.printStackTrace();

        }
    }//GEN-LAST:event_btnChooseAvatarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(()
                -> new EditProfileFirstTime("test").setVisible(true)
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChooseAvatar;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblAvatarTitle;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBio;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblDisplayName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextArea txtBio;
    private javax.swing.JTextField txtDisplayName;
    // End of variables declaration//GEN-END:variables
}
