/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AppThucDon.dao.FormDangNhap;

import AppThucDon.database.Database;
import AppThucDon.view.Mainlayout;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

public class EditProfileFirstTime extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditProfileFirstTime.class.getName());

    private String username;

    private String avatarPath = "";

    /*
constructor nhận username
     */
    public EditProfileFirstTime(
            String username
    ) {

        initComponents();

        setSize(
                1000,
                900
        );

        setLocationRelativeTo(
                null
        );

        this.username = username;

        // load dữ liệu cũ
        txtDisplayName.setText(
                CurrentUser.displayName
        );

        txtBio.setText(
                CurrentUser.bio
        );

        avatarPath
                = CurrentUser.avatar;

        try {

            if (avatarPath != null
                    && !avatarPath.isEmpty()) {

                ImageIcon icon
                        = new ImageIcon(
                                avatarPath
                        );

                Image img
                        = icon.getImage()
                                .getScaledInstance(
                                        150,
                                        150,
                                        Image.SCALE_SMOOTH
                                );

                lblAvatar.setText("");

                lblAvatar.setIcon(
                        new ImageIcon(img)
                );

            }

        } catch (Exception e) {

            e.printStackTrace();

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        lblAvatar = new javax.swing.JLabel();
        btnChooseAvatar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtDisplayName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtBio = new javax.swing.JTextArea();
        btnSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Chỉnh sửa ảnh đại diện :");

        lblAvatar.setBackground(new java.awt.Color(153, 153, 153));
        lblAvatar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAvatar.setText("Chưa chọn ảnh");
        lblAvatar.setMaximumSize(new java.awt.Dimension(150, 150));
        lblAvatar.setMinimumSize(new java.awt.Dimension(150, 150));
        lblAvatar.setOpaque(true);
        lblAvatar.setPreferredSize(new java.awt.Dimension(150, 150));

        btnChooseAvatar.setText("Chọn ảnh");
        btnChooseAvatar.addActionListener(this::btnChooseAvatarActionPerformed);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Nhập tên người dùng :");

        txtDisplayName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDisplayName.addActionListener(this::txtDisplayNameActionPerformed);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Phần mô tả :");

        txtBio.setColumns(20);
        txtBio.setRows(5);
        jScrollPane1.setViewportView(txtBio);

        btnSave.setText("Lưu ");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Edit Your ProFiles");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(txtDisplayName, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(383, 383, 383)
                        .addComponent(btnChooseAvatar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 348, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(433, 433, 433))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addGap(156, 156, 156))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(188, 188, 188))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnChooseAvatar)
                .addGap(12, 12, 12)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtDisplayName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDisplayNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDisplayNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDisplayNameActionPerformed

    private void btnChooseAvatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseAvatarActionPerformed
        try {

            JFileChooser chooser
                    = new JFileChooser();

            int result
                    = chooser.showOpenDialog(this);

            if (result
                    == JFileChooser.APPROVE_OPTION) {

                File file
                        = chooser.getSelectedFile();

                String fileName
                        = System.currentTimeMillis()
                        + "_"
                        + file.getName();

                File dir
                        = new File(
                                "uploads"
                        );

                if (!dir.exists()) {

                    dir.mkdirs();

                }

                File save
                        = new File(
                                dir,
                                fileName
                        );

                Files.copy(
                        file.toPath(),
                        save.toPath(),
                        StandardCopyOption.REPLACE_EXISTING
                );

                avatarPath
                        = save.getPath();

                ImageIcon icon
                        = new ImageIcon(
                                avatarPath
                        );

                Image img
                        = icon.getImage()
                                .getScaledInstance(
                                        150,
                                        150,
                                        Image.SCALE_SMOOTH
                                );

                lblAvatar.setText("");

                lblAvatar.setIcon(
                        new ImageIcon(
                                img
                        )
                );

            }

        } catch (Exception e) {

            e.printStackTrace();

        }
    }//GEN-LAST:event_btnChooseAvatarActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {

            Connection conn
                    = Database.getConnection();

            String sql
                    = "UPDATE Users "
                    + "SET "
                    + "DisplayName=?,"
                    + "Avatar=?,"
                    + "Bio=? "
                    + "WHERE Username=?";

            PreparedStatement ps
                    = conn.prepareStatement(
                            sql
                    );

            ps.setString(
                    1,
                    txtDisplayName.getText()
            );

            ps.setString(
                    2,
                    avatarPath
            );

            ps.setString(
                    3,
                    txtBio.getText()
            );

            ps.setString(
                    4,
                    username
            );

            ps.executeUpdate();
            CurrentUser.username
                    = username;

            CurrentUser.displayName
                    = txtDisplayName.getText();

            CurrentUser.bio
                    = txtBio.getText();

            CurrentUser.avatar
                    = avatarPath;

            JOptionPane.showMessageDialog(
                    this,
                    "Lưu thành công!"
            );

            Mainlayout main
                    = new Mainlayout();

            main.setVisible(
                    true
            );

            dispose();

        } catch (Exception e) {

            e.printStackTrace();

        }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(()
                -> new EditProfileFirstTime("test").setVisible(true)
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChooseAvatar;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JTextArea txtBio;
    private javax.swing.JTextField txtDisplayName;
    // End of variables declaration//GEN-END:variables
}
