/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AppThucDon.dao.FormDangNhap;

import AppThucDon.dao.FormDangNhap.EditProfileFirstTime;
import AppThucDon.dao.FormDangNhap.JFrameLoginForm;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class UserPanel extends javax.swing.JPanel {

    private String username;

    public UserPanel(
            String username,
            String displayName,
            String avatar,
            String bio
    ) {

        initComponents();

        txtBio.setEditable(false);

        this.username = username;

        loadUser(
                username,
                displayName,
                avatar,
                bio
        );
    }

    public UserPanel() {
        initComponents();

        txtBio.setEditable(false);
    }

    private void loadUser(
            String username,
            String displayName,
            String avatar,
            String bio
    ) {

        // hiện @username
        lblUserID.setText(
                username == null
                        ? ""
                        : "@" + username
        );

        // hiện tên thật
        lblDisplayName.setText(
                displayName == null
                        ? username
                        : displayName
        );

        txtBio.setText(
                bio == null
                        ? ""
                        : bio
        );

        try {

            if (avatar != null
                    && !avatar.isEmpty()) {

                File f = new File(avatar);

                if (f.exists()) {

                    ImageIcon icon
                            = new ImageIcon(
                                    avatar
                            );

                    Image img
                            = icon
                                    .getImage()
                                    .getScaledInstance(
                                            150,
                                            150,
                                            Image.SCALE_SMOOTH
                                    );

                    lblAvatar.setText("");

                    lblAvatar.setIcon(
                            new ImageIcon(img)
                    );

                }

            }

        } catch (Exception e) {

            e.printStackTrace();

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDisplayName = new javax.swing.JLabel();
        lblAvatar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtBio = new javax.swing.JTextArea();
        btnEdit = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblUserID = new javax.swing.JLabel();

        lblDisplayName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        lblAvatar.setBackground(new java.awt.Color(153, 153, 153));
        lblAvatar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAvatar.setText("Chưa chọn ảnh");
        lblAvatar.setMaximumSize(new java.awt.Dimension(150, 150));
        lblAvatar.setMinimumSize(new java.awt.Dimension(150, 150));
        lblAvatar.setOpaque(true);
        lblAvatar.setPreferredSize(new java.awt.Dimension(150, 150));

        txtBio.setColumns(20);
        txtBio.setRows(5);
        jScrollPane1.setViewportView(txtBio);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);

        btnLogout.setText("LogOut");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        lblUserID.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(btnLogout))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                        .addComponent(btnEdit)))
                .addGap(69, 69, 69))
            .addGroup(layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDisplayName, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(btnEdit)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogout)
                        .addGap(181, 181, 181))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblDisplayName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(189, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int confirm
                = JOptionPane.showConfirmDialog(
                        this,
                        "Đăng xuất?",
                        "Xác nhận",
                        JOptionPane.YES_NO_OPTION
                );

        if (confirm
                == JOptionPane.YES_OPTION) {

            CurrentUser.userId = null;
            CurrentUser.username = null;
            CurrentUser.displayName = null;
            CurrentUser.avatar = null;
            CurrentUser.bio = null;

            JFrameLoginForm login
                    = new JFrameLoginForm();

            login.setVisible(true);

            javax.swing.SwingUtilities
                    .getWindowAncestor(this)
                    .dispose();

        }


    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        EditProfileFirstTime edit
                = new EditProfileFirstTime(
                        CurrentUser.username
                );

        edit.setVisible(true);

        javax.swing.SwingUtilities
                .getWindowAncestor(this)
                .dispose();
    }//GEN-LAST:event_btnEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnLogout;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblDisplayName;
    private javax.swing.JLabel lblUserID;
    private javax.swing.JTextArea txtBio;
    // End of variables declaration//GEN-END:variables
}
