/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AppThucDon.view;

import java.awt.CardLayout;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import AppThucDon.view.icon.PillButton;
import AppThucDon.model.MonAn;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.io.File;
import javax.swing.JScrollPane;
/**
 *
 * @author loan phuong
 */
public class Congthuccuatoito extends javax.swing.JPanel {

    /**
     * Creates new form Phongto
     */

    private Goiytheogio parent;
    public Congthuccuatoito() {
    initComponents();
                    jScrollPane2.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPane3.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
    txtNguyenlieu.setLineWrap(true);
    txtNguyenlieu.setWrapStyleWord(true);
    jTextArea1.setLineWrap(true);
    jTextArea1.setWrapStyleWord(true);
}
    public Congthuccuatoito(Goiytheogio parent) {
        initComponents();
        this.parent = parent;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTenmon = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSuact = new PillButton();
        btnXuatfile = new PillButton();
        btnXoact = new PillButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtNguyenlieu = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(253, 246, 237));

        jLabel4.setText("Mô tả công thức");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Tên món ăn");
        jLabel2.setToolTipText("");

        jLabel1.setText("xem ảnh");

        jLabel3.setText("Đây là loại món ăn :");

        jLabel5.setText("Thời gian cook :");

        btnSuact.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSuact.setText("Sửa công thức");

        btnXuatfile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXuatfile.setText("Xuất file");
        btnXuatfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatfileActionPerformed(evt);
            }
        });

        btnXoact.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXoact.setText("Xóa công thức");

        txtNguyenlieu.setColumns(20);
        txtNguyenlieu.setRows(5);
        jScrollPane3.setViewportView(txtNguyenlieu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTenmon))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnXoact, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSuact, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnXuatfile, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenmon, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSuact, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(btnXuatfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnXuatfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatfileActionPerformed
        JFileChooser chooser = new JFileChooser();
    chooser.setDialogTitle("Lưu công thức");

    int result = chooser.showSaveDialog(this);

    if (result != JFileChooser.APPROVE_OPTION) {
        return;
    }

    File file = chooser.getSelectedFile();

    // tự thêm đuôi .txt nếu người dùng chưa nhập
    if (!file.getName().toLowerCase().endsWith(".txt")) {
        file = new File(file.getAbsolutePath() + ".txt");
    }

    try (BufferedWriter bw = new BufferedWriter(new FileWriter(file))) {

        bw.write("========== CÔNG THỨC NẤU ĂN ==========");
        bw.newLine();
        bw.newLine();

        bw.write("Tên món ăn: " + txtTenmon.getText());
        bw.newLine();

        bw.write(jLabel3.getText());   // Loại món ăn
        bw.newLine();

        bw.write(jLabel5.getText());   // Thời gian nấu
        bw.newLine();



        bw.write("NGUYÊN LIỆU");
        bw.newLine();
        bw.write(txtNguyenlieu.getText());
        bw.newLine();
        bw.newLine();

        bw.write("MÔ TẢ CÔNG THỨC");
        bw.newLine();
        bw.write(jTextArea1.getText());

        JOptionPane.showMessageDialog(
                this,
                "Xuất file thành công!"
        );

    } catch (Exception e) {
        JOptionPane.showMessageDialog(
                this,
                "Lỗi xuất file: " + e.getMessage()
        );
    }
    }//GEN-LAST:event_btnXuatfileActionPerformed
    public void setData(MonAn mon) {
    txtTenmon.setText(mon.getTenMon());
    txtNguyenlieu.setText(mon.getNguyenLieu()); // nếu có field này
    jTextArea1.setText(mon.getMoTa()); // mô tả
    jLabel5.setText("Thời gian cook: " + mon.getThoiGian() + " phút");
    jLabel3.setText("Loại món: " + mon.getLoaiMon());
 String path = "images/" + mon.getLinkAnh();

    java.net.URL url =
            getClass()
            .getClassLoader()
            .getResource(path);

    if(url != null){

        ImageIcon icon =
                new ImageIcon(url);

        Image img =
                icon.getImage()
                .getScaledInstance(
                        494,
                        291,
                        Image.SCALE_SMOOTH);

        jLabel1.setIcon(
                new ImageIcon(img));

        jLabel1.setText("");
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuact;
    private javax.swing.JButton btnXoact;
    private javax.swing.JButton btnXuatfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea txtNguyenlieu;
    private javax.swing.JTextField txtTenmon;
    // End of variables declaration//GEN-END:variables
}
