/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AppThucDon.view;

import AppThucDon.model.MonAn;
import AppThucDon.service.MonAnService;
import java.awt.Component;
import java.awt.Dimension;
import java.util.List;
import javax.swing.BoxLayout;
import AppThucDon.view.Congthuccuatoito;
import javax.swing.JScrollPane;

/**
 *
 * @author loan phuong
 */
public class Congthuccuatoi extends javax.swing.JPanel {

    /**
     * Creates new form Luucongthuc
     */private MonAnService service = new MonAnService();
    public Congthuccuatoi(int maNguoiTao) {
        initComponents();
         jScrollPane1.setBorder(null);
         jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
         
    pnlDaydu.setLayout(new BoxLayout(pnlDaydu, BoxLayout.Y_AXIS));

    List<MonAn> danhSach = service.layDanhSachMonDaTao(maNguoiTao);

    for (MonAn mon : danhSach) {
        Congthuccuatoito p = new Congthuccuatoito();

        // 👉 truyền data vào panel con (bước 2)
        p.setData(mon);

        Dimension d = p.getPreferredSize();
        p.setMaximumSize(new Dimension(Integer.MAX_VALUE, d.height));
        p.setAlignmentX(Component.LEFT_ALIGNMENT);

        pnlDaydu.add(p);
        pnlDaydu.add(javax.swing.Box.createVerticalStrut(20));
    }

    pnlDaydu.revalidate();
    pnlDaydu.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pnlDaydu = new javax.swing.JPanel();

        pnlDaydu.setLayout(new javax.swing.BoxLayout(pnlDaydu, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane1.setViewportView(pnlDaydu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlDaydu;
    // End of variables declaration//GEN-END:variables
}
