/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AppThucDon.view;

import java.awt.CardLayout;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import AppThucDon.view.icon.PillButton;
import AppThucDon.model.MonAn;
import AppThucDon.service.MonAnService;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.io.File;
import javax.swing.JScrollPane;
/**
 *
 * @author loan phuong
 */
public class Congthuccuatoito extends javax.swing.JPanel {

    /**
     * Creates new form Phongto
     */

    
    private MonAn monAnHienTai;
    private Congthuccuatoi parent;
    private boolean isEditing = false;
private MonAnService service = new MonAnService();

    public Congthuccuatoito() {
    initComponents();

initUI();
}
    public Congthuccuatoito(Congthuccuatoi parent) {
        initComponents();
        this.parent = parent;
initUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTenmon = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSuact = new PillButton();
        btnXuatfile = new PillButton();
        btnXoact = new PillButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtNguyenlieu = new javax.swing.JTextArea();
        btnXacNhan = new javax.swing.JButton();
        txtDanhgia = new javax.swing.JTextField();

        setBackground(new java.awt.Color(253, 246, 237));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Công thức");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Tên món ăn");
        jLabel2.setToolTipText("");

        jLabel1.setText("xem ảnh");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Đây là loại món ăn :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        btnSuact.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSuact.setText("Sửa công thức");
        btnSuact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuactActionPerformed(evt);
            }
        });

        btnXuatfile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnXuatfile.setText("Xuất file");
        btnXuatfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatfileActionPerformed(evt);
            }
        });

        btnXoact.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnXoact.setText("Xóa công thức");
        btnXoact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoactActionPerformed(evt);
            }
        });

        txtNguyenlieu.setColumns(20);
        txtNguyenlieu.setRows(5);
        jScrollPane3.setViewportView(txtNguyenlieu);

        btnXacNhan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnXacNhan.setText("Xác nhận ");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        txtDanhgia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTenmon))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnXoact, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnSuact, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnXacNhan, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnXuatfile, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(txtDanhgia, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenmon, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDanhgia, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnXuatfile, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(btnSuact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXacNhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnXuatfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatfileActionPerformed
        JFileChooser chooser = new JFileChooser();
    chooser.setDialogTitle("Lưu công thức");

    int result = chooser.showSaveDialog(this);

    if (result != JFileChooser.APPROVE_OPTION) {
        return;
    }

    File file = chooser.getSelectedFile();

    // tự thêm đuôi .txt nếu người dùng chưa nhập
    if (!file.getName().toLowerCase().endsWith(".txt")) {
        file = new File(file.getAbsolutePath() + ".txt");
    }

    try (BufferedWriter bw = new BufferedWriter(new FileWriter(file))) {

        bw.write("========== CÔNG THỨC NẤU ĂN ==========");
        bw.newLine();
        bw.newLine();

        bw.write("Tên món ăn: " + txtTenmon.getText());
        bw.newLine();

        bw.write(jLabel3.getText());   // Loại món ăn
        bw.newLine();

        bw.write(jLabel5.getText());   // Thời gian nấu
        bw.newLine();



        bw.write("NGUYÊN LIỆU");
        bw.newLine();
        bw.write(txtNguyenlieu.getText());
        bw.newLine();
        bw.newLine();

        bw.write("MÔ TẢ CÔNG THỨC");
        bw.newLine();
        bw.write(jTextArea1.getText());

        JOptionPane.showMessageDialog(
                this,
                "Xuất file thành công!"
        );

    } catch (Exception e) {
        JOptionPane.showMessageDialog(
                this,
                "Lỗi xuất file: " + e.getMessage()
        );
    }
    }//GEN-LAST:event_btnXuatfileActionPerformed

    private void btnXoactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoactActionPerformed
        xoaCongThuc();
    }//GEN-LAST:event_btnXoactActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
 if (monAnHienTai == null) return;

    monAnHienTai.setTenMon(txtTenmon.getText());
    monAnHienTai.setNguyenLieu(txtNguyenlieu.getText());
    monAnHienTai.setMoTa(jTextArea1.getText());

    boolean ok = service.capNhatMonAn(monAnHienTai);

    if (ok) {
        JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
        setEditMode(false);
    } else {
        JOptionPane.showMessageDialog(this, "Cập nhật thất bại!");
    }
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void btnSuactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuactActionPerformed
        setEditMode(true);
    }//GEN-LAST:event_btnSuactActionPerformed
    
    
    public void setData(MonAn mon) {
        txtNguyenlieu.setLineWrap(true);
txtNguyenlieu.setWrapStyleWord(true);

jTextArea1.setLineWrap(true);
jTextArea1.setWrapStyleWord(true);

        this.monAnHienTai = mon;
    txtTenmon.setText(mon.getTenMon());
    txtNguyenlieu.setText(mon.getNguyenLieu()); // nếu có field này
    jTextArea1.setText(mon.getMoTa()); // mô tả
    jLabel5.setText("Thời gian cook: " + mon.getThoiGian() + " phút");
    jLabel3.setText("Loại món: " + mon.getLoaiMon());
    txtDanhgia.setText(String.format("%.1f", mon.getDanhGia()));
    setEditMode(false);
 String path = "images/" + mon.getLinkAnh();

    java.net.URL url =
            getClass()
            .getClassLoader()
            .getResource(path);

    if(url != null){

        ImageIcon icon =
                new ImageIcon(url);

        Image img =
                icon.getImage()
                .getScaledInstance(
                        494,
                        291,
                        Image.SCALE_SMOOTH);

        jLabel1.setIcon(
                new ImageIcon(img));

        jLabel1.setText("");
    }
}
    
    private void xoaCongThuc() {

    if (monAnHienTai == null) return;

    int confirm = JOptionPane.showConfirmDialog(
            this,
            "Bạn có chắc muốn xóa không?",
            "Xóa",
            JOptionPane.YES_NO_OPTION
    );

    if (confirm != JOptionPane.YES_OPTION) return;

    boolean ok = service.xoaMonAn(monAnHienTai.getMaMon());

    if (ok) {
        JOptionPane.showMessageDialog(this, "Đã xóa!");

        // ⭐ reload toàn bộ list
        if (parent != null) {
            parent.loadDanhSach();
        }
    } else {
        JOptionPane.showMessageDialog(this, "Xóa thất bại!");
    }
}

    
    private void setEditMode(boolean editing) {
    isEditing = editing;

    txtTenmon.setEditable(editing);
    txtNguyenlieu.setEditable(editing);
    jTextArea1.setEditable(editing);

    btnSuact.setVisible(!editing);
    btnXacNhan.setVisible(editing); // nút mới bạn sẽ thêm
}
    
    private void initUI() {

    setEditMode(false);

    btnXacNhan.setVisible(false);

    txtTenmon.setEditable(false);
    txtNguyenlieu.setEditable(false);
    jTextArea1.setEditable(false);

    txtNguyenlieu.setLineWrap(true);
    txtNguyenlieu.setWrapStyleWord(true);

    jTextArea1.setLineWrap(true);
    jTextArea1.setWrapStyleWord(true);

    jScrollPane3.setViewportView(txtNguyenlieu);
    jScrollPane2.setViewportView(jTextArea1);

    txtNguyenlieu.setMinimumSize(new Dimension(0, 0));
    jTextArea1.setMinimumSize(new Dimension(0, 0));

    jScrollPane2.setPreferredSize(new Dimension(0, 120));
    jScrollPane3.setPreferredSize(new Dimension(0, 120));

    txtNguyenlieu.setColumns(1);
    jTextArea1.setColumns(1);
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuact;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JButton btnXoact;
    private javax.swing.JButton btnXuatfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtDanhgia;
    private javax.swing.JTextArea txtNguyenlieu;
    private javax.swing.JTextField txtTenmon;
    // End of variables declaration//GEN-END:variables
}
