/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AppThucDon.view;

import AppThucDon.dao.FormDangNhap.CurrentUser;
import java.awt.CardLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import AppThucDon.service.MonAnService;
import AppThucDon.model.MonAn;
import java.util.List;

/**
 *
 * @author loan phuong
 */
public class Dexuat extends javax.swing.JPanel {

    /**
     * Creates new form Goiyct
     */private Dexuatto dexuatto;
    public Dexuat() {
        initComponents();

dexuatto = new Dexuatto(this);

    this.add(jScrollPane1, "DEXUAT");
    this.add(dexuatto, "PHONGTO");

    CardLayout cl = (CardLayout) this.getLayout();
    cl.show(this, "DEXUAT");
    taiDuLieu();

    }
    public void taiDuLieu() {

    panelDexuat.removeAll();

    MonAnService monanservice = new MonAnService();
    List<MonAn> danhsach = monanservice.getGoiYMonAn(10);

    for (MonAn i : danhsach) {

        thunho card = new thunho(
                i.getMaMon(),
                i.getTenMon(),
                "Tác giả " + i.getTenNguoiTao(),
                i.getDanhGia() + " Sao",
                i.getThoiGian() + " phút",
                i.getLinkAnh()
        );

        card.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {

                dexuatto.hienThiMonAn(i);

                CardLayout cl = (CardLayout) Dexuat.this.getLayout();
                cl.show(Dexuat.this, "PHONGTO");
            }
        });

        panelDexuat.add(card);
    }

    panelDexuat.revalidate();
    panelDexuat.repaint();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelDexuat = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 0, 0));
        setForeground(new java.awt.Color(255, 0, 0));
        setLayout(new java.awt.CardLayout());

        panelDexuat.setLayout(new java.awt.GridLayout(0, 2, 5, 40));
        jScrollPane1.setViewportView(panelDexuat);

        add(jScrollPane1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelDexuat;
    // End of variables declaration//GEN-END:variables
}
