/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AppThucDon.view;

import AppThucDon.dao.FormDangNhap.CurrentUser;
import java.awt.CardLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author loan phuong
 */
public class Dexuat extends javax.swing.JPanel {

    /**
     * Creates new form Goiyct
     */
    public Dexuat() {
        initComponents();
        Dexuatto Dexuatto = new Dexuatto(this);
        this.add(jScrollPane1, "DEXUAT");
        this.add(Dexuatto, "PHONGTO");
        CardLayout cl = (CardLayout) this.getLayout();
        cl.show(this, "DEXUAT");
        
        for(int i = 1; i <= 10; i++){
     thunho card = new thunho(
            "Món " + i,
            "Tác giả " + i,
            "4." + i%5 + "⭐",
            "30 phút",
            "Nguyên liệu..."
     );



card.addMouseListener(new MouseAdapter() {
    @Override
    public void mouseClicked(MouseEvent e) {
        System.out.println("Da click");
        
        CardLayout cl = (CardLayout) Dexuat.this.getLayout();
            cl.show(Dexuat.this, "PHONGTO");
    }
            });
    panelDexuat.add(card);
}
panelDexuat.revalidate();
panelDexuat.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelDexuat = new javax.swing.JPanel();

        setLayout(new java.awt.CardLayout());

        panelDexuat.setLayout(new java.awt.GridLayout(0, 2, 5, 40));
        jScrollPane1.setViewportView(panelDexuat);

        add(jScrollPane1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelDexuat;
    // End of variables declaration//GEN-END:variables
}
