/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AppThucDon.view;

import AppThucDon.dao.FormDangNhap.CurrentUser;
import java.awt.CardLayout;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.Box;
import javax.swing.BoxLayout;

/**
 *
 * @author loan phuong
 */
public class Goiyct extends javax.swing.JPanel {

    /**
     * Creates new form Goiyct
     */
    public Goiyct() {
        initComponents();
        panelGoiy.setLayout(
        new BoxLayout(panelGoiy, BoxLayout.Y_AXIS)
    );

        Goiyto pnlPhongto = new Goiyto(this);
        this.add(jScrollPane1, "GOIY");
        this.add(pnlPhongto, "PHONGTO");
        CardLayout cl = (CardLayout) this.getLayout();
        cl.show(this, "GOIY");
        
        for(int i = 1; i <= 10; i++){
     thunhotheogio card = new thunhotheogio(
            "Món " + i,
            "Tác giả " + i,
            "4." + i%5 + "⭐",
            "30 phút",
            "Nguyên liệu..."

    );
card.setAlignmentX(Component.CENTER_ALIGNMENT);


card.addMouseListener(new MouseAdapter() {
    @Override
    public void mouseClicked(MouseEvent e) {
        System.out.println("Da click");
        
        CardLayout cl = (CardLayout) Goiyct.this.getLayout();
            cl.show(Goiyct.this, "PHONGTO");
    }
});
    panelGoiy.add(card);
    panelGoiy.add(Box.createVerticalStrut(40));
}
panelGoiy.revalidate();
panelGoiy.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelGoiy = new javax.swing.JPanel();

        setLayout(new java.awt.CardLayout());

        panelGoiy.setLayout(new javax.swing.BoxLayout(panelGoiy, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane1.setViewportView(panelGoiy);

        add(jScrollPane1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelGoiy;
    // End of variables declaration//GEN-END:variables
}
