/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AppThucDon.view;

import AppThucDon.dao.FormDangNhap.CurrentUser;
import AppThucDon.model.MonAn;
import AppThucDon.service.MonAnService;
import java.awt.CardLayout;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.Box;
import javax.swing.BoxLayout;
import java.util.List;

/**
 *
 * @author loan phuong
 */
public class Goiytheogio extends javax.swing.JPanel {
private Goiytheogioto pnlPhongto;
    /**
     * Creates new form Goiyct
     */
    public Goiytheogio() {

    initComponents();

    panelGoiy.setLayout(
            new BoxLayout(panelGoiy, BoxLayout.Y_AXIS));

    pnlPhongto = new Goiytheogioto(this);

    // Chỉ thêm panel phóng to
    this.add(pnlPhongto, "PHONGTO");

    CardLayout cl = (CardLayout) getLayout();
    cl.show(this, "card2");

    taiDuLieu();
    System.out.println("Goiytheogio = " + this);
}    
    
    public void taiDuLieu() {

    panelGoiy.removeAll();

    MonAnService service = new MonAnService();

    List<MonAn> ds = service.goiYAnGiBayGio();
System.out.println("So mon = " + ds.size());
    for (MonAn mon : ds) {

        thunhotheogio card = new thunhotheogio(
                mon.getTenMon(),
                mon.getTenNguoiTao(),
                mon.getDanhGia() + "⭐",
                mon.getThoiGian() + " phút",
                mon.getLinkAnh()
        );

        card.setAlignmentX(Component.CENTER_ALIGNMENT);

        card.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {

                pnlPhongto.hienThiMonAn(mon);

                CardLayout cl =
                        (CardLayout) Goiytheogio.this.getLayout();

                cl.show(Goiytheogio.this, "PHONGTO");
            }
        });

        panelGoiy.add(card);
        panelGoiy.add(Box.createVerticalStrut(40));
    }
System.out.println("Component = " + panelGoiy.getComponentCount());
    panelGoiy.revalidate();
    panelGoiy.repaint();
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelGoiy = new javax.swing.JPanel();

        setLayout(new java.awt.CardLayout());

        panelGoiy.setLayout(new javax.swing.BoxLayout(panelGoiy, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane1.setViewportView(panelGoiy);

        add(jScrollPane1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelGoiy;
    // End of variables declaration//GEN-END:variables
}
