/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AppThucDon.view;

import java.awt.Component;
import java.awt.Dimension;
import javax.swing.BoxLayout;

/**
 *
 * @author loan phuong
 */
public class Luucongthuc extends javax.swing.JPanel {

    /**
     * Creates new form Luucongthuc
     */
    public Luucongthuc() {
        initComponents();
        jScrollPane1.setBorder(null);
        pnlDaydu.setLayout(new BoxLayout(pnlDaydu, BoxLayout.Y_AXIS));
        for (int i = 1; i <= 10; i++) {
    Hienthicongthuccuatoi p = new Hienthicongthuccuatoi();
    Dimension d = p.getPreferredSize();
p.setMaximumSize(new Dimension(Integer.MAX_VALUE, d.height));
p.setAlignmentX(Component.LEFT_ALIGNMENT);
    pnlDaydu.add(p);
    pnlDaydu.add(javax.swing.Box.createVerticalStrut(40));
}
    pnlDaydu.revalidate();
    pnlDaydu.repaint();
    jScrollPane1.setHorizontalScrollBarPolicy(
        javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pnlDaydu = new javax.swing.JPanel();

        pnlDaydu.setLayout(new javax.swing.BoxLayout(pnlDaydu, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane1.setViewportView(pnlDaydu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlDaydu;
    // End of variables declaration//GEN-END:variables
}
