/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AppThucDon.view;

import AppThucDon.view.icon.SearchTextField;
import AppThucDon.dao.FormDangNhap.CurrentUser;
import AppThucDon.dao.FormDangNhap.UserPanel;
import AppThucDon.view.icon.PillButton;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import java.util.*;

/**
 *
 * @author loan phuong
 */
public class Mainlayout extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Mainlayout.class.getName());
    CardLayout card;

    /**
     * Creates new form lamlayout
     */
    public Mainlayout() {
        initComponents();
        
        addHoverEffect(btnHome);
        addHoverEffect(jButton2);
        addHoverEffect(btnCuatoi);
        addHoverEffect(btnThemct);
        addHoverEffect(btnsetting);
        addHoverEffect(btnDexuat);
        addHoverEffect(btnYeuthich);
        btnHome.setOpaque(true);
        jButton2.setOpaque(true);
        btnCuatoi.setOpaque(true);
        btnThemct.setOpaque(true);
        btnsetting.setOpaque(true);
        btnDexuat.setOpaque(true);
        btnYeuthich.setOpaque(true);

        btnHome.setContentAreaFilled(true);
        jButton2.setContentAreaFilled(true);
        btnCuatoi.setContentAreaFilled(true);
        btnThemct.setContentAreaFilled(true);
        btnsetting.setContentAreaFilled(true);
        btnDexuat.setContentAreaFilled(true);
        btnYeuthich.setContentAreaFilled(true);

        resetMenu();
        setSelected(btnHome);
        ImageIcon icon = new ImageIcon(
                getClass().getResource("/images/Rauma.png"));

        Image img = icon.getImage().getScaledInstance(
                100, 100, Image.SCALE_SMOOTH);

        btnHome.setIcon(new ImageIcon(img));

        menu1.setOpaque(true);

        card = new CardLayout();
        content2.setLayout(card);

        content2.add(new homepanel(), "Home");
        content2.add(new Congthucmoi(), "Ctmoi");
        content2.add(
                new UserPanel(
                        CurrentUser.username,
                        CurrentUser.displayName,
                        CurrentUser.avatar,
                        CurrentUser.bio
                ),
                "setting"
        );
        content2.add(new Goiyct(), "Goiy");
        content2.add(new Congthuccuatoi(), "Luuct");
        content2.add(new Dexuat(), "Dexuat");

        card.show(content2, "Home");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu1 = new javax.swing.JPanel();
        btnCuatoi = new javax.swing.JButton();
        btnThemct = new javax.swing.JButton();
        btnsetting = new javax.swing.JButton();
        jTextField1 = new SearchTextField();
        btnHome = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        content2 = new javax.swing.JPanel();
        btnTimkiem = new javax.swing.JButton();
        btnDexuat = new javax.swing.JButton();
        btnYeuthich = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 233, 240));

        menu1.setBackground(new java.awt.Color(255, 248, 240));
        menu1.setForeground(new java.awt.Color(255, 102, 102));

        btnCuatoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCuatoi.setForeground(new java.awt.Color(153, 153, 153));
        btnCuatoi.setText("Công thức của tôi");
        btnCuatoi.setBorder(null);
        btnCuatoi.setContentAreaFilled(false);
        btnCuatoi.setFocusPainted(false);
        btnCuatoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuatoiActionPerformed(evt);
            }
        });

        btnThemct.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThemct.setForeground(new java.awt.Color(153, 153, 153));
        btnThemct.setText("Thêm công thức");
        btnThemct.setBorder(null);
        btnThemct.setContentAreaFilled(false);
        btnThemct.setFocusPainted(false);
        btnThemct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemctActionPerformed(evt);
            }
        });

        btnsetting.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnsetting.setText("Đăng xuất");
        btnsetting.setBorder(null);
        btnsetting.setContentAreaFilled(false);
        btnsetting.setFocusPainted(false);
        btnsetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsettingActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        btnHome.setText("Home");
        btnHome.setBorderPainted(false);
        btnHome.setContentAreaFilled(false);
        btnHome.setFocusPainted(false);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 153, 153));
        jButton2.setText(" Ăn gì bây giờ?");
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        content2.setPreferredSize(new java.awt.Dimension(661, 570));

        javax.swing.GroupLayout content2Layout = new javax.swing.GroupLayout(content2);
        content2.setLayout(content2Layout);
        content2Layout.setHorizontalGroup(
            content2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        content2Layout.setVerticalGroup(
            content2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnTimkiem.setText("tìm kiếm");

        btnDexuat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDexuat.setText("Đề xuất");
        btnDexuat.setBorder(null);
        btnDexuat.setFocusPainted(false);
        btnDexuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDexuatActionPerformed(evt);
            }
        });

        btnYeuthich.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnYeuthich.setText("Yêu thích");
        btnYeuthich.setBorder(null);
        btnYeuthich.setFocusPainted(false);
        btnYeuthich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYeuthichActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menu1Layout = new javax.swing.GroupLayout(menu1);
        menu1.setLayout(menu1Layout);
        menu1Layout.setHorizontalGroup(
            menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnsetting, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menu1Layout.createSequentialGroup()
                        .addGroup(menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnThemct, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btnYeuthich, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnCuatoi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                        .addComponent(btnTimkiem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnHome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(btnDexuat, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content2, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        menu1Layout.setVerticalGroup(
            menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDexuat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCuatoi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnYeuthich, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnThemct, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnsetting, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addComponent(content2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCuatoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuatoiActionPerformed
        card.show(content2, "Luuct");
        resetMenu();
        setSelected(btnCuatoi);
    }//GEN-LAST:event_btnCuatoiActionPerformed

    private void btnThemctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemctActionPerformed
        card.show(content2, "Ctmoi");
        resetMenu();
        setSelected(btnThemct);
    }//GEN-LAST:event_btnThemctActionPerformed

    private void btnsettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsettingActionPerformed
        card.show(content2, "setting");
        resetMenu();
        setSelected(btnsetting);
    }//GEN-LAST:event_btnsettingActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        card.show(content2, "Goiy");
        resetMenu();
        setSelected(jButton2);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        card.show(content2, "Home");
        resetMenu();
        setSelected(btnHome);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnDexuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDexuatActionPerformed
        card.show(content2, "Dexuat");
        resetMenu();
        setSelected(btnDexuat);
    }//GEN-LAST:event_btnDexuatActionPerformed

    private void btnYeuthichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYeuthichActionPerformed
        
        resetMenu();
        setSelected(btnYeuthich);
    }//GEN-LAST:event_btnYeuthichActionPerformed

    
    private void resetMenu() {
        Color bg = menu1.getBackground();
        Color text = new Color(20, 20, 20);
        btnHome.setBackground(bg);
        btnHome.setForeground(text);
        jButton2.setBackground(bg);
        jButton2.setForeground(text);
        btnCuatoi.setBackground(bg);
        btnCuatoi.setForeground(text);
        btnThemct.setBackground(bg);
        btnThemct.setForeground(text);
        btnsetting.setBackground(bg);
        btnsetting.setForeground(text);
        btnDexuat.setBackground(bg);
        btnDexuat.setForeground(text);
        btnYeuthich.setBackground(bg);
        btnYeuthich.setForeground(text);
    }

    private void setSelected(javax.swing.JButton btn) {
        btn.setBackground(new Color(255, 120, 0));
        btn.setForeground(new Color(255, 255, 255));
    }
    
        private void addHoverEffect(javax.swing.JButton btn) {

    Color hover = new Color(255, 160, 40);    // làm nút sáng lên khi rê chuột

    Color normal = menu1.getBackground(); // đang áp dụng cho toàn bộ button menu

    btn.setBackground(normal);// 🌫 set nền mặc định

    btn.addMouseListener(new java.awt.event.MouseAdapter() {

        @Override
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            if (btn.getBackground().equals(new Color(255, 120, 0))) {
                return; // đang selected thì không đổi hover
            }
            btn.setBackground(hover);
        }

        @Override
        public void mouseExited(java.awt.event.MouseEvent evt) {
            if (btn.getBackground().equals(new Color(255, 120, 0))) {
                return;
            }
            btn.setBackground(normal);
        }
    });
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCuatoi;
    private javax.swing.JButton btnDexuat;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnThemct;
    private javax.swing.JButton btnTimkiem;
    private javax.swing.JButton btnYeuthich;
    private javax.swing.JButton btnsetting;
    private javax.swing.JPanel content2;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel menu1;
    // End of variables declaration//GEN-END:variables
}
