/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AppThucDon.view;

import AppThucDon.dao.FormDangNhap.CurrentUser;
import AppThucDon.service.YeuThichService;
import AppThucDon.view.icon.IconTraitim;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author loan phuong
 */
public class thunhotheogio extends javax.swing.JPanel {


    
private boolean daYeuThich = false;
    /**
     * Creates new form thunho

     */
public thunhotheogio(String tenMon, String tacGia, String sao, String thoiGian, String linkAnh) {
        initComponents();
        
        // 1. Gán text trước
        lblTenct.setText(tenMon);
        lblTacgia.setText(tacGia);
        lblSao.setText(sao);
        lblThoigian.setText(thoiGian);
        
        setPreferredSize(new java.awt.Dimension(373, 390));
        setMaximumSize(new Dimension(373, 390));
        
        // 2. Xử lý load ảnh an toàn từ resources
        String path = "images/" + linkAnh;
        java.net.URL url = getClass().getClassLoader().getResource(path);

        if (url == null) {
            
            lblAnh.setText("No Image"); // Hiển thị chữ thay thế để không lỗi
        } else {
            try {
                ImageIcon icon = new ImageIcon(url);
                
                // Lấy kích thước mong muốn thiết kế (185x210), phòng khi lblAnh chưa render (bằng 0)
                int targetWidth = lblAnh.getWidth() > 0 ? lblAnh.getWidth() : 361;
                int targetHeight = lblAnh.getHeight() > 0 ? lblAnh.getHeight() : 214;

                Image img = icon.getImage().getScaledInstance(
                        targetWidth,
                        targetHeight,
                        Image.SCALE_SMOOTH);

                lblAnh.setIcon(new ImageIcon(img));
                lblAnh.setText(""); // Xóa chữ "Ảnh" mặc định đi
            } catch (Exception e) {
                System.out.println("Lỗi xử lý ảnh: " + e.getMessage());
                lblAnh.setText("Error Image");
            }
        }
        
        IconTraitim.setHeart(btnTraitim, daYeuThich);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAnh = new javax.swing.JLabel();
        lblTenct = new javax.swing.JLabel();
        lblTacgia = new javax.swing.JLabel();
        lblSao = new javax.swing.JLabel();
        lblThoigian = new javax.swing.JLabel();
        btnTraitim = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 153, 0));
        setForeground(new java.awt.Color(255, 204, 153));

        lblAnh.setText("Ảnh");

        lblTenct.setText("Tên món");
        lblTenct.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        lblTacgia.setText("Ten tac gia");
        lblTacgia.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        lblSao.setText("Sao");
        lblSao.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        lblThoigian.setText("Thòi gian");
        lblThoigian.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        btnTraitim.setText("jButton1");
        btnTraitim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraitimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAnh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTenct, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblSao, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTacgia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblThoigian, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTraitim, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSao, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(lblTenct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblThoigian, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTraitim, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTacgia, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTraitimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraitimActionPerformed
    daYeuThich = !daYeuThich;

    IconTraitim.setHeart(btnTraitim, daYeuThich);
    }//GEN-LAST:event_btnTraitimActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTraitim;
    private javax.swing.JLabel lblAnh;
    private javax.swing.JLabel lblSao;
    private javax.swing.JLabel lblTacgia;
    private javax.swing.JLabel lblTenct;
    private javax.swing.JLabel lblThoigian;
    // End of variables declaration//GEN-END:variables
}
