/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AppThucDon.view;

import javax.swing.Box;

/**
 *
 * @author loan phuong
 */
public class Timkiem extends javax.swing.JPanel {

    /**
     * Creates new form Timkiem
     */
    public Timkiem() {
        initComponents();
        jScrollPane1.setBorder(null);
        for(int i = 0; i < 5; i++) {

    Yeuthichto p = new Yeuthichto();

    panelTimkiem.add(p);
    panelTimkiem.add(
            Box.createVerticalStrut(20));
}

panelTimkiem.revalidate();
panelTimkiem.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelTimkiem = new javax.swing.JPanel();

        panelTimkiem.setLayout(new javax.swing.BoxLayout(panelTimkiem, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane1.setViewportView(panelTimkiem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(764, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(614, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelTimkiem;
    // End of variables declaration//GEN-END:variables
}
