/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AppThucDon.view;

import AppThucDon.view.icon.PillButton;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author loan phuong
 */
public class Timkiemto extends javax.swing.JPanel {

    /**
     * Creates new form Goiyto
     */

    public Timkiemto() {
        initComponents();
            // chiều rộng có thể thay đổi, nhưng chiều cao phải cố định
    setPreferredSize(new Dimension(760, 610));
    System.out.println(getPreferredSize());
    }
  
    public void setMonAn(AppThucDon.model.MonAn monAn) {
        if (monAn == null) return; // Nếu không có dữ liệu thì bỏ qua

        // 1. Hiển thị tên món ăn vào JTextField
        txtTenmon.setText(monAn.getTenMon());
        
        // 2. Hiển thị loại món ăn vào JLabel
        jLabel3.setText("Đây là loại món ăn : " + monAn.getLoaiMon());
        
        // 3. Hiển thị thời gian nấu vào JLabel
        jLabel5.setText("Thời gian nấu ăn : " + monAn.getThoiGian() + " phút");
        
        // 4. Hiển thị nguyên liệu vào JTextArea
        txtNguyenlieu.setText(monAn.getNguyenLieu());
        
        // 5. Hiển thị mô tả công thức vào JTextArea
        jTextArea1.setText(monAn.getMoTa());
        
        // 6. Hiển thị đánh giá hiện tại (nếu bạn muốn)
        txtDanhgia.setText(String.valueOf(monAn.getDanhGia()) + " Sao");

        // 7. Xử lý hiển thị ảnh (Vẽ ảnh lên jLabel1)
        if (monAn.getLinkAnh() != null && !monAn.getLinkAnh().trim().isEmpty()) {
            try {
                // Đọc file ảnh từ đường dẫn lưu trong DB
                javax.swing.ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource(monAn.getLinkAnh()));
                
                // Thu nhỏ ảnh cho vừa với khung jLabel1 (300x300 pixel)
                java.awt.Image img = icon.getImage().getScaledInstance(300, 300, java.awt.Image.SCALE_SMOOTH);
                
                // Đặt ảnh đã thu nhỏ vào jLabel1
                jLabel1.setText(""); // Xóa chữ "xem ảnh" mặc định
                jLabel1.setIcon(new javax.swing.ImageIcon(img));
                
            } catch (Exception e) {
                // Nếu đường dẫn ảnh bị lỗi (không tìm thấy file), in ra lỗi để debug
                System.out.println("Không thể tải ảnh cho món " + monAn.getTenMon() + ": " + e.getMessage());
                jLabel1.setText("Lỗi hiển thị ảnh");
                jLabel1.setIcon(null);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTenmon = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnLuuyeuthich = new javax.swing.JButton();
        btnXuatfile = new PillButton();
        txtDanhgia = new javax.swing.JTextField();
        btnLuudanhgia = new PillButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtNguyenlieu = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(253, 246, 237));

        jLabel4.setText("Mô tả công thức");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Tên món ăn");
        jLabel2.setToolTipText("");

        jLabel1.setText("xem ảnh");

        jLabel3.setText("Đây là loại món ăn :");

        jLabel5.setText("Thời gian nấu ăn :");

        btnLuuyeuthich.setText("Lưu yêu thích");
        btnLuuyeuthich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuyeuthichActionPerformed(evt);
            }
        });

        btnXuatfile.setText("Xuất file");
        btnXuatfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatfileActionPerformed(evt);
            }
        });

        txtDanhgia.setText("jTextField1");

        btnLuudanhgia.setText("Đánh giá ct");
        btnLuudanhgia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuudanhgiaActionPerformed(evt);
            }
        });

        txtNguyenlieu.setColumns(20);
        txtNguyenlieu.setRows(5);
        jScrollPane3.setViewportView(txtNguyenlieu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                        .addComponent(btnLuuyeuthich, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtDanhgia, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnLuudanhgia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnXuatfile, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(txtTenmon, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenmon, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLuuyeuthich, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXuatfile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(txtDanhgia, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLuudanhgia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnXuatfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatfileActionPerformed
        JFileChooser chooser = new JFileChooser();
    chooser.setDialogTitle("Lưu công thức");

    int result = chooser.showSaveDialog(this);

    if (result != JFileChooser.APPROVE_OPTION) {
        return;
    }

    File file = chooser.getSelectedFile();

    // tự thêm đuôi .txt nếu người dùng chưa nhập
    if (!file.getName().toLowerCase().endsWith(".txt")) {
        file = new File(file.getAbsolutePath() + ".txt");
    }

    try (BufferedWriter bw = new BufferedWriter(new FileWriter(file))) {

        bw.write("========== CÔNG THỨC NẤU ĂN ==========");
        bw.newLine();
        bw.newLine();

        bw.write("Tên món ăn: " + txtTenmon.getText());
        bw.newLine();

        bw.write(jLabel3.getText());   // Loại món ăn
        bw.newLine();

        bw.write(jLabel5.getText());   // Thời gian nấu
        bw.newLine();

        bw.write("Đánh giá: " + txtDanhgia.getText());
        bw.newLine();
        bw.newLine();

        bw.write("NGUYÊN LIỆU");
        bw.newLine();
        bw.write(txtNguyenlieu.getText());
        bw.newLine();
        bw.newLine();

        bw.write("MÔ TẢ CÔNG THỨC");
        bw.newLine();
        bw.write(jTextArea1.getText());

        JOptionPane.showMessageDialog(
                this,
                "Xuất file thành công!"
        );

    } catch (Exception e) {
        JOptionPane.showMessageDialog(
                this,
                "Lỗi xuất file: " + e.getMessage()
        );
    }
    }//GEN-LAST:event_btnXuatfileActionPerformed

    private void btnLuudanhgiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuudanhgiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLuudanhgiaActionPerformed

    private void btnLuuyeuthichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuyeuthichActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLuuyeuthichActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuudanhgia;
    private javax.swing.JButton btnLuuyeuthich;
    private javax.swing.JButton btnXuatfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtDanhgia;
    private javax.swing.JTextArea txtNguyenlieu;
    private javax.swing.JTextField txtTenmon;
    // End of variables declaration//GEN-END:variables
}
