/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AppThucDon.view;

import AppThucDon.model.MonAn;
import java.awt.Component;
import java.awt.Dimension;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import AppThucDon.view.Timkiemto;
import java.awt.Color;
import java.awt.Font;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;

/**
 *
 * @author loan phuong
 */
public class Timkiem extends javax.swing.JPanel {

    /**
     * Creates new form Timkiem
     */
    public Timkiem() {
        initComponents();
    panelTimkiem.setLayout(
            new BoxLayout(panelTimkiem, BoxLayout.Y_AXIS));

    jScrollPane1.setHorizontalScrollBarPolicy(
            JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);

    jScrollPane1.setVerticalScrollBarPolicy(
            JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);

    }

    // =================================================================
    // HÀM NHẬN DỮ LIỆU TỪ MAINLAYOUT VÀ VẼ LÊN MÀN HÌNH (BƯỚC 3)
    // =================================================================
    public void hienThiKetQua(java.util.List<AppThucDon.model.MonAn> danhSach, int soLuong) {
         panelTimkiem.removeAll();

     panelTimkiem.removeAll();

JLabel lblKetQua = new JLabel(
        "Đã tìm thấy " + soLuong + " công thức phù hợp.",
        SwingConstants.CENTER);

lblKetQua.setFont(
        new Font("Segoe UI", Font.BOLD, 22));

lblKetQua.setForeground(
        new Color(255,120,0));

lblKetQua.setAlignmentX(Component.LEFT_ALIGNMENT);
lblKetQua.setHorizontalAlignment(SwingConstants.CENTER);
lblKetQua.setMaximumSize(
        new Dimension(Integer.MAX_VALUE, 50));

    panelTimkiem.add(lblKetQua);
    panelTimkiem.add(Box.createVerticalStrut(20));

    for (MonAn monAn : danhSach) {

        Timkiemto p = new Timkiemto();

        p.setMonAn(monAn);

        p.setAlignmentX(Component.LEFT_ALIGNMENT);

        Dimension d = p.getPreferredSize();

        p.setMaximumSize(
                new Dimension(
                        Integer.MAX_VALUE,
                        d.height));

        panelTimkiem.add(p);
        panelTimkiem.add(Box.createVerticalStrut(20));
    }

    panelTimkiem.revalidate();
    panelTimkiem.repaint();

    SwingUtilities.invokeLater(() ->
            jScrollPane1.getVerticalScrollBar()
                    .setValue(0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelTimkiem = new javax.swing.JPanel();

        panelTimkiem.setLayout(new javax.swing.BoxLayout(panelTimkiem, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(panelTimkiem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelTimkiem;
    // End of variables declaration//GEN-END:variables
}
