/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AppThucDon.view;

import javax.swing.Box;

/**
 *
 * @author loan phuong
 */
public class Timkiem extends javax.swing.JPanel {

    /**
     * Creates new form Timkiem
     */
    public Timkiem() {
        initComponents();
        jScrollPane1.setBorder(null); // Đã sửa tên đúng và xóa code nháp
    }

    // =================================================================
    // HÀM NHẬN DỮ LIỆU TỪ MAINLAYOUT VÀ VẼ LÊN MÀN HÌNH (BƯỚC 3)
    // =================================================================
    public void hienThiKetQua(java.util.List<AppThucDon.model.MonAn> danhSach, int soLuong) {
        panelTimkiem.removeAll(); 
        
        // Hiện số lượng
        javax.swing.JLabel lblKetQua = new javax.swing.JLabel(" Đã tìm thấy " + soLuong + " công thức phù hợp.");
        lblKetQua.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        lblKetQua.setForeground(new java.awt.Color(255, 120, 0));
        
        panelTimkiem.add(lblKetQua);
        panelTimkiem.add(javax.swing.Box.createVerticalStrut(20)); // Đã viết tên đầy đủ nên chữ Box sẽ không bị đỏ nữa

        // Hiện danh sách món ăn
        if (soLuong > 0) {
            for (AppThucDon.model.MonAn monAn : danhSach) {
                Yeuthichto p = new Yeuthichto();
                
                 p.setMonAn(monAn); 
                
                panelTimkiem.add(p);
                panelTimkiem.add(javax.swing.Box.createVerticalStrut(20));
            }
        }

        panelTimkiem.revalidate();
        panelTimkiem.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelTimkiem = new javax.swing.JPanel();

        panelTimkiem.setLayout(new javax.swing.BoxLayout(panelTimkiem, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(panelTimkiem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelTimkiem;
    // End of variables declaration//GEN-END:variables
}
