/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AppThucDon.view;
import AppThucDon.view.Yeuthichto;
import java.awt.Component;
import java.awt.Dimension;
import javax.swing.Box;
import AppThucDon.dao.FormDangNhap.CurrentUser;
import AppThucDon.service.YeuThichService;
import AppThucDon.model.MonAn;
/**
 *
 * @author loan phuong
 */
public class Yeuthich extends javax.swing.JPanel {
private YeuThichService yeuThichService = new YeuThichService();
    /**
     * Creates new form Yeuthich
     */
    public Yeuthich() {
        initComponents();
                jScrollPane1.setBorder(null);


panelYeuthich.setLayout(
        new javax.swing.BoxLayout(
            panelYeuthich,
            javax.swing.BoxLayout.Y_AXIS
        )
    );

    taiDuLieu();

    }
    
    public void taiDuLieu() {

    panelYeuthich.removeAll();

    java.util.List<MonAn> ds =
            yeuThichService.layDanhSachMonYeuThich(CurrentUser.userId);

    for (MonAn mon : ds) {

        Yeuthichto p = new Yeuthichto(this);

        p.setMonAn(mon);

        p.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);

        java.awt.Dimension d = p.getPreferredSize();


        panelYeuthich.add(p);
        panelYeuthich.add(javax.swing.Box.createVerticalStrut(20));
    }

    panelYeuthich.revalidate();
    panelYeuthich.repaint();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelYeuthich = new javax.swing.JPanel();

        panelYeuthich.setLayout(new javax.swing.BoxLayout(panelYeuthich, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane1.setViewportView(panelYeuthich);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelYeuthich;
    // End of variables declaration//GEN-END:variables
}
