/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AppThucDon.view;

import AppThucDon.dao.FormDangNhap.CurrentUser;
import AppThucDon.model.MonAn;
import AppThucDon.service.YeuThichService;
import AppThucDon.view.icon.PillButton;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import AppThucDon.view.icon.IconTraitim;
import javax.swing.JButton;
import java.awt.BorderLayout;
import javax.swing.JScrollPane;


/**
 *
 * @author loan phuong
 */
public class Yeuthichto extends javax.swing.JPanel {

    /**
     * Creates new form Goiyto
     */
private MonAn monHienTai;
private Yeuthich yeuThichPanel;
private YeuThichService yeuThichService = new YeuThichService();

    public Yeuthichto(Yeuthich panel) {
    this.yeuThichPanel = panel;

    initComponents();

    btnLuuyeuthich.setText("");

    jScrollPane2.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPane3.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);

    txtNguyenlieu.setLineWrap(true);
    txtNguyenlieu.setWrapStyleWord(true);

    jTextArea1.setLineWrap(true);
    jTextArea1.setWrapStyleWord(true);
    }
  
    public void setMonAn(AppThucDon.model.MonAn monAn) {
        this.monHienTai = monAn;
        if (monAn == null) return; // Nếu không có dữ liệu thì bỏ qua

        // 1. Hiển thị tên món ăn vào JTextField
        txtTenmon.setText(monAn.getTenMon());
        
        // 2. Hiển thị loại món ăn vào JLabel
        jLabel3.setText("loại món ăn : " + monAn.getLoaiMon());
        
        // 3. Hiển thị thời gian nấu vào JLabel
        jLabel5.setText("Thời gian nấu : " + monAn.getThoiGian() + " phút");
        
        // 4. Hiển thị nguyên liệu vào JTextArea
        txtNguyenlieu.setText(monAn.getNguyenLieu());
        
        // 5. Hiển thị mô tả công thức vào JTextArea
        jTextArea1.setText(monAn.getMoTa());
        
        // 6. Hiển thị đánh giá hiện tại (nếu bạn muốn)
        txtDanhgia.setText("Công thức này được đánh giá: " +String.valueOf(monAn.getDanhGia()) + " Sao");

        // 7. Xử lý hiển thị ảnh (Vẽ ảnh lên jLabel1)
if (monAn.getLinkAnh() != null && !monAn.getLinkAnh().trim().isEmpty()) {

    String path = "images/" + monAn.getLinkAnh();

    java.net.URL url = getClass().getClassLoader().getResource(path);

    if (url != null) {

        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(url);

        java.awt.Image img = icon.getImage().getScaledInstance(
                494,
                300,
                java.awt.Image.SCALE_SMOOTH);

        jLabel1.setIcon(new javax.swing.ImageIcon(img));
        jLabel1.setText("");

    } else {

        System.out.println("Không tìm thấy ảnh: " + path);

        jLabel1.setIcon(null);
        jLabel1.setText("Không có ảnh");
    }
}
        
        boolean daThich = yeuThichService.isDaYeuThich(
        CurrentUser.userId,
        monAn.getMaMon());

IconTraitim.setHeart(btnLuuyeuthich, daThich);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTenmon = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnLuuyeuthich = new javax.swing.JButton();
        btnXuatfile = new PillButton();
        txtDanhgia = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtNguyenlieu = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(253, 246, 237));

        jLabel4.setText("Mô tả công thức");

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 191, 63)));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Tên món ăn");
        jLabel2.setToolTipText("");

        jLabel1.setText("xem ảnh");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        btnLuuyeuthich.setText("Lưu yêu thích");
        btnLuuyeuthich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuyeuthichActionPerformed(evt);
            }
        });

        btnXuatfile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnXuatfile.setText("Xuất file");
        btnXuatfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatfileActionPerformed(evt);
            }
        });

        txtDanhgia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDanhgia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDanhgiaActionPerformed(evt);
            }
        });

        jScrollPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 191, 63)));

        txtNguyenlieu.setColumns(20);
        txtNguyenlieu.setRows(5);
        jScrollPane3.setViewportView(txtNguyenlieu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnLuuyeuthich, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtDanhgia)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnXuatfile, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(16, 16, 16))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(txtTenmon, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenmon, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLuuyeuthich, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXuatfile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(txtDanhgia, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnXuatfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatfileActionPerformed
        JFileChooser chooser = new JFileChooser();
    chooser.setDialogTitle("Lưu công thức");

    int result = chooser.showSaveDialog(this);

    if (result != JFileChooser.APPROVE_OPTION) {
        return;
    }

    File file = chooser.getSelectedFile();

    // tự thêm đuôi .txt nếu người dùng chưa nhập
    if (!file.getName().toLowerCase().endsWith(".txt")) {
        file = new File(file.getAbsolutePath() + ".txt");
    }

    try (BufferedWriter bw = new BufferedWriter(new FileWriter(file))) {

        bw.write("========== CÔNG THỨC NẤU ĂN ==========");
        bw.newLine();
        bw.newLine();

        bw.write("Tên món ăn: " + txtTenmon.getText());
        bw.newLine();

        bw.write(jLabel3.getText());   // Loại món ăn
        bw.newLine();

        bw.write(jLabel5.getText());   // Thời gian nấu
        bw.newLine();

        bw.write("Đánh giá: " + txtDanhgia.getText());
        bw.newLine();
        bw.newLine();

        bw.write("NGUYÊN LIỆU");
        bw.newLine();
        bw.write(txtNguyenlieu.getText());
        bw.newLine();
        bw.newLine();

        bw.write("MÔ TẢ CÔNG THỨC");
        bw.newLine();
        bw.write(jTextArea1.getText());

        JOptionPane.showMessageDialog(
                this,
                "Xuất file thành công!"
        );

    } catch (Exception e) {
        JOptionPane.showMessageDialog(
                this,
                "Lỗi xuất file: " + e.getMessage()
        );
    }
    }//GEN-LAST:event_btnXuatfileActionPerformed

    private void btnLuuyeuthichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuyeuthichActionPerformed
    int result = yeuThichService.YeuThichMonAn(
            CurrentUser.userId,
            monHienTai.getMaMon());

    if (result == 1 || result == 2) {

        boolean daThich = yeuThichService.isDaYeuThich(
                CurrentUser.userId,
                monHienTai.getMaMon());

        IconTraitim.setHeart(btnLuuyeuthich, daThich);

        if (yeuThichPanel != null) {
            yeuThichPanel.taiDuLieu();
        }

    } else if (result == -2) {

        JOptionPane.showMessageDialog(this, "Vui lòng đăng nhập");

    } else {

        JOptionPane.showMessageDialog(this, "Có lỗi xảy ra");
    }
    }//GEN-LAST:event_btnLuuyeuthichActionPerformed

    private void txtDanhgiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDanhgiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDanhgiaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuuyeuthich;
    private javax.swing.JButton btnXuatfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtDanhgia;
    private javax.swing.JTextArea txtNguyenlieu;
    private javax.swing.JTextField txtTenmon;
    // End of variables declaration//GEN-END:variables
}
