/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package batdau.hocptpmud;
import java.awt.*;
import javax.swing.*;


/**
 *
 * @author loan phuong
 */
public class homepanel extends javax.swing.JPanel {

    /**
     * Creates new form homepanel
     */
    private Image backgroundImage;
    
    public homepanel() {
        initComponents();
        java.net.URL url =
            getClass().getResource("/images/Picture1.png");


    if(url != null){
        backgroundImage = new ImageIcon(url).getImage();
    }
    else{
        System.out.println("Khong tim thay anh");
    }
    }

    
    

@Override
protected void paintComponent(Graphics g) {
    super.paintComponent(g);
    if (backgroundImage != null){
        g.drawImage(backgroundImage, 0, 0, getWidth(), getHeight(), this);
    
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jButton1)
                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jButton1)
                .addContainerGap(213, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
