package cookingapp;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author Admin
 */
public class RecipePanel extends javax.swing.JPanel {

    /**
     * Creates new form RecipePanel
     */
    public RecipePanel() {

        initComponents();

        setPreferredSize(
                new java.awt.Dimension(
                        700,
                        700
                )
        );

        lblUsername.setText(
                "Time No"
        );

        lblRecipeName.setText(
                "Bún bò Huế"
        );

        txtDescription.setText(
                "Thịt bò, bún, rau..."
        );

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsername = new javax.swing.JLabel();
        lblRecipeName = new javax.swing.JLabel();
        lblRecipeImage = new javax.swing.JLabel();
        lblAvatar1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        btnLike = new javax.swing.JButton();
        btnComment = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        lblUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsername.setText("Username");

        lblRecipeName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRecipeName.setText("Tên Món Ăn ");

        lblRecipeImage.setBackground(new java.awt.Color(153, 153, 153));
        lblRecipeImage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRecipeImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRecipeImage.setText("Chưa chọn ảnh");
        lblRecipeImage.setMaximumSize(new java.awt.Dimension(150, 150));
        lblRecipeImage.setMinimumSize(new java.awt.Dimension(150, 150));
        lblRecipeImage.setOpaque(true);
        lblRecipeImage.setPreferredSize(new java.awt.Dimension(150, 150));

        lblAvatar1.setBackground(new java.awt.Color(153, 153, 153));
        lblAvatar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAvatar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAvatar1.setText("Chưa chọn ảnh");
        lblAvatar1.setMaximumSize(new java.awt.Dimension(150, 150));
        lblAvatar1.setMinimumSize(new java.awt.Dimension(150, 150));
        lblAvatar1.setOpaque(true);
        lblAvatar1.setPreferredSize(new java.awt.Dimension(150, 150));

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane1.setViewportView(txtDescription);

        btnLike.setText("Like");

        btnComment.setText("Comment");

        btnSave.setText("Save");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLike)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnComment)
                        .addGap(127, 127, 127)
                        .addComponent(btnSave)
                        .addGap(88, 88, 88))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRecipeName, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRecipeImage, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 22, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(lblAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblRecipeName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRecipeImage, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnComment)
                    .addComponent(btnLike))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComment;
    private javax.swing.JButton btnLike;
    private javax.swing.JButton btnSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAvatar1;
    private javax.swing.JLabel lblRecipeImage;
    private javax.swing.JLabel lblRecipeName;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextArea txtDescription;
    // End of variables declaration//GEN-END:variables
}
